make:
	gcc -o myls myls-rocchi.c
	gcc -o mysearch mysearch-rocchi.c
	gcc -o mystat mystat-rocchi.c
	gcc -o mytail mytail-rocchi.c

runmyls:
	./myls

runmysearch:
	./mysearch

runmystat:
	./mystat

runmytail:
	./mytail

clean:
	rm ./smyls
	rm ./mysearch
	rm ./mystat
	rm ./mytail
